[versions]
kotlin = "2.0.21"
asm = "9.9"
gson = "2.10.1"

stitch = "0.6.2"
tiny-remapper = "0.12.0"
clazz-tweaker = "0.1.1"
mapping-io = "0.8.0"
lorenz-tiny = "4.0.2"
mercury = "0.4.3"
mercury-mixin = "0.2.2"
loom-native = "0.2.0"
unpick = "3.0.0-beta.13"

# Plugins
spotless = "7.2.1"
test-retry = "1.6.2"
checkstyle = "10.26.1"
codenarc = "3.6.0"

[libraries]
# Loom compile libraries
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-analysis = { module = "org.ow2.asm:asm-analysis", version.ref = "asm" }
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
asm-tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }
asm-util = { module = "org.ow2.asm:asm-util", version.ref = "asm" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

fabric-stitch = { module = "net.fabricmc:stitch", version.ref = "stitch" }
fabric-tiny-remapper = { module = "net.fabricmc:tiny-remapper", version.ref = "tiny-remapper" }
fabric-clazz-tweaker = { module = "net.fabricmc:class-tweaker", version.ref = "clazz-tweaker" }
fabric-mapping-io = { module = "net.fabricmc:mapping-io", version.ref = "mapping-io" }
fabric-lorenz-tiny = { module = "net.fabricmc:lorenz-tiny", version.ref = "lorenz-tiny" }
fabric-mercury = { module = "net.fabricmc:mercury", version.ref = "mercury" }
fabric-mercury-mixin = { module = "net.fabricmc:mercurymixin", version.ref = "mercury-mixin" }
fabric-loom-nativelib = { module = "net.fabricmc:fabric-loom-native", version.ref = "loom-native" }
fabric-unpick = { module = "net.fabricmc.unpick:unpick", version.ref = "unpick" }
fabric-unpick-utils = { module = "net.fabricmc.unpick:unpick-format-utils", version.ref = "unpick" }

# Misc
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-metadata = { module = "org.jetbrains.kotlin:kotlin-metadata-jvm", version.ref = "kotlin" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
retry = { id = "org.gradle.test-retry", version.ref = "test-retry" }

[bundles]
asm = ["asm", "asm-analysis", "asm-commons", "asm-tree", "asm-util"]
