[versions]
fabric-loader = "0.16.9"
fabric-api = "0.106.1+1.20.1"
minecraft = "1.20.1"

[libraries]
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
