[versions]
fabric-loader = "0.16.14"
fabric-api = "0.88.0+1.20.1"
mixin = "0.15.3+mixin.0.8.7"
junit = "5.13.4"
spock = "2.3-groovy-3.0"

[libraries]
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
mixin = { module = "net.fabricmc:sponge-mixin", version.ref = "mixin" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
spock = { module = "org.spockframework:spock-core", version.ref = "spock" }
